import { Injectable } from "@nestjs/common"

import PDFDocument from "pdfkit"
import PptxGenJS from "pptxgenjs"
import * as XLSX from "xlsx"

import { PrismaService } from "../../prisma/prisma.service"

import { HrAnalyticsDelegatedService } from "./hr-analytics-delegated.service"
import { resolveDateRange, type HrAnalyticsFilters } from "./hr-analytics-filters.util"
import { HrAnalyticsService } from "./hr-analytics.service"
import { formatReportPeriod, REPORT_TARGETS, REPORT_THEME, resolveLogoPath } from "./report-theme"

/** pptxgenjs's addTable() wants each row as TableCell[] (`{ text }`
 *  objects), not plain strings — this just wraps a row of plain strings
 *  into that shape so the table-building code below can stay readable. */
function tableRow(cells: Array<string | number>): PptxGenJS.TableCell[] {
  return cells.map((cell) => ({ text: String(cell) }))
}

/** Same per-department bar palette as the dashboard's charts.tsx `COLORS`
 *  array (bare hex, no "#" — that's the format pptxgenjs's chartColors
 *  option wants, unlike PDFKit elsewhere in this codebase which needs the
 *  "#" prefix). Keep these two arrays in sync if the dashboard's palette
 *  ever changes. */
const CHART_PALETTE = ["0A2647", "B8860B", "3B2412", "2E7D6B", "7F77DD", "D85A30", "5DCAA5", "D4537E"]

/** Mirrors charts.tsx's fillRateColor() so a department's PPTX bar color
 *  agrees with the dashboard's red/amber/green thresholds. */
function fillRateColor(rate: number): string {
  if (rate < 50) return "D4537E"
  if (rate < 75) return "B8860B"
  return "5DCAA5"
}

/** One row of the Custom Report Builder's section checklist (see
 *  hr-analytics-export.controller.ts's `reports/custom` route and the
 *  client's custom-report-dialog.tsx). Every section shows a date-range
 *  picker; `caveat` flags the two (Departments, Positions) whose underlying
 *  query is a snapshot of current org structure with no date dimension at
 *  all (positionFillRate/orgStructureAnalytics don't accept dateFrom/dateTo)
 *  — the range is still collected and passed through for a consistent UI,
 *  it just won't change those two sections' output, which the dialog
 *  surfaces via this caveat rather than silently doing nothing. Recruitment
 *  is deliberately excluded — see HrAnalyticsDelegatedService's class doc
 *  comment for why it can't be filtered by date/department at all — so it
 *  wouldn't behave consistently with every other section here. */
export interface ReportSectionMeta {
  key: string
  label: string
  description: string
  supportsDateRange: boolean
  caveat?: string
}

export const REPORT_SECTIONS: ReportSectionMeta[] = [
  { key: "overview", label: "Overview & Headcount", description: "Total staff, joiners, exits, and top-line KPIs", supportsDateRange: true },
  { key: "demographics", label: "Gender Report", description: "Male/female split, age brackets, contract type by gender", supportsDateRange: true },
  {
    key: "departments",
    label: "Departments",
    description: "Org structure and headcount by department",
    supportsDateRange: true,
    caveat: "Current org structure — date range does not change this section",
  },
  {
    key: "positions",
    label: "Positions",
    description: "All positions with fill rates by department",
    supportsDateRange: true,
    caveat: "Current org structure — date range does not change this section",
  },
  { key: "leave", label: "Leave Report", description: "Annual leave, sick, maternity — by department and type", supportsDateRange: true },
  { key: "performance", label: "Performance Report", description: "Rating distribution (bell curve), ratings & variance by department", supportsDateRange: true },
  { key: "exit", label: "Exit Report", description: "Departures by reason, type and department", supportsDateRange: true },
  { key: "turnover", label: "Turnover & Retention", description: "Attrition rate, retention %, year-over-year change", supportsDateRange: true },
  { key: "learning", label: "Learning & Development", description: "Training completion and AML compliance", supportsDateRange: true },
]

const REPORT_SECTION_KEYS = new Set(REPORT_SECTIONS.map((s) => s.key))

export interface CustomReportSectionInput {
  key: string
  dateFrom?: string
  dateTo?: string
}

/** Cover-page/slide metadata — resolved once per export and reused by every
 *  format. "Generated by" falls back to a generic label when actingEmployeeId
 *  isn't available (defensive; every current call site does pass it) or
 *  doesn't resolve to a real employee. */
interface ReportCoverInfo {
  reportTitle: string
  periodLabel: string
  departmentLabel: string | null
  generatedAtLabel: string
  generatedByLabel: string
}

interface ExportBundle {
  totalStaff: Awaited<ReturnType<HrAnalyticsService["totalStaff"]>>
  averageAge: Awaited<ReturnType<HrAnalyticsService["averageAge"]>>
  bandDistribution: Awaited<ReturnType<HrAnalyticsService["bandDistribution"]>>
  attritionRate: Awaited<ReturnType<HrAnalyticsService["attritionRate"]>>
  positionFillRate: Awaited<ReturnType<HrAnalyticsService["positionFillRate"]>>
  leaveUtilization: Awaited<ReturnType<HrAnalyticsService["leaveUtilizationSummary"]>>
  employeeDistribution: Awaited<ReturnType<HrAnalyticsService["employeeDistributionByDepartment"]>>
  exitSummary: Awaited<ReturnType<HrAnalyticsService["exitSummary"]>>
  demographics: Awaited<ReturnType<HrAnalyticsService["employeeDemographics"]>>
  performanceDistribution: Awaited<ReturnType<HrAnalyticsDelegatedService["performanceDistribution"]>>
  learning: Awaited<ReturnType<HrAnalyticsDelegatedService["learningAnalyticsFor"]>>
}

/** Data shape for the Custom Report Builder — one optional slot per
 *  REPORT_SECTIONS entry, `null` when that section wasn't selected. Mirrors
 *  ExportBundle's Awaited<ReturnType<...>> convention above. */
interface CustomReportBundle {
  overview: {
    totalStaff: Awaited<ReturnType<HrAnalyticsService["totalStaff"]>>
    averageAge: Awaited<ReturnType<HrAnalyticsService["averageAge"]>>
    bandDistribution: Awaited<ReturnType<HrAnalyticsService["bandDistribution"]>>
  } | null
  demographics: Awaited<ReturnType<HrAnalyticsService["employeeDemographics"]>> | null
  departments: {
    employeeDistribution: Awaited<ReturnType<HrAnalyticsService["employeeDistributionByDepartment"]>>
    orgStructure: Awaited<ReturnType<HrAnalyticsService["orgStructureAnalytics"]>>
  } | null
  positions: Awaited<ReturnType<HrAnalyticsService["positionFillRate"]>> | null
  leave: {
    utilization: Awaited<ReturnType<HrAnalyticsService["leaveUtilizationSummary"]>>
    summary: Awaited<ReturnType<HrAnalyticsDelegatedService["leaveSummary"]>>
  } | null
  performance: {
    distribution: Awaited<ReturnType<HrAnalyticsDelegatedService["performanceDistribution"]>>
    byDepartment: Awaited<ReturnType<HrAnalyticsDelegatedService["performanceByDepartment"]>>
  } | null
  exit: Awaited<ReturnType<HrAnalyticsService["exitSummary"]>> | null
  turnover: Awaited<ReturnType<HrAnalyticsService["attritionRate"]>> | null
  learning: Awaited<ReturnType<HrAnalyticsDelegatedService["learningAnalyticsFor"]>> | null
}

/**
 * Report export — Excel, CSV, PDF, PowerPoint. Excel uses the `xlsx`
 * package already installed for the Bulk Import framework's template
 * downloads (see spreadsheet.util.ts) rather than adding a second Excel
 * library. PDF mirrors ExecutiveDashboardPdfService's section() pattern.
 * PowerPoint uses pptxgenjs's native chart types (bar/pie/line) so the
 * generated .pptx has real, editable PowerPoint charts, not embedded images.
 */
@Injectable()
export class HrAnalyticsExportService {
  constructor(
    private readonly hrAnalyticsService: HrAnalyticsService,
    private readonly delegated: HrAnalyticsDelegatedService,
    private readonly prisma: PrismaService
  ) {}

  /** Resolves the cover page/slide's metadata: report period (from the same
   *  date-range logic every KPI query already uses), the filtered
   *  department's name (if any), and who ran the export. A direct Prisma
   *  lookup rather than going through EmployeesService/DepartmentsService —
   *  this only needs two names, not either service's full include graph. */
  private async buildCoverInfo(filters: HrAnalyticsFilters, actingEmployeeId?: string): Promise<ReportCoverInfo> {
    const [department, generatedBy] = await Promise.all([
      filters.departmentId ? this.prisma.department.findUnique({ where: { id: filters.departmentId }, select: { name: true } }) : Promise.resolve(null),
      actingEmployeeId ? this.prisma.employee.findUnique({ where: { employeeNumber: actingEmployeeId }, select: { firstName: true, lastName: true } }) : Promise.resolve(null),
    ])

    return {
      reportTitle: "HR Workforce Dashboard",
      periodLabel: formatReportPeriod(resolveDateRange(filters)),
      departmentLabel: department?.name ?? null,
      generatedAtLabel: new Date().toLocaleString("en-GB", { dateStyle: "long", timeStyle: "short" }),
      generatedByLabel: generatedBy ? `${generatedBy.firstName} ${generatedBy.lastName}` : "NCBA Rwanda PeopleSuite",
    }
  }

  /** The spec's "Executive Summary" paragraph — one deterministic sentence
   *  built from numbers already in the bundle, not an LLM call (see this
   *  module's own doc comment on why AI-generated insights were scoped
   *  out). Mirrors the spec's own worked example sentence structure. */
  private buildExecutiveSummary(bundle: ExportBundle): string {
    const meetingOrExceeding = bundle.performanceDistribution
      .filter((r: { rank: number; actualPercentage: number }) => r.rank >= 3)
      .reduce((sum: number, r: { actualPercentage: number }) => sum + r.actualPercentage, 0)
    const amlLine = bundle.learning.amlCompletionRate !== null ? `, while AML training compliance reached ${bundle.learning.amlCompletionRate}%` : ""

    return (
      `During the selected reporting period, NCBA Rwanda had ${bundle.totalStaff.activeCount} active employees, ` +
      `with a ${bundle.positionFillRate.fillRate}% position fill rate and a ${bundle.attritionRate.rate}% attrition rate. ` +
      `Performance ratings remained ${meetingOrExceeding >= 60 ? "strong" : "mixed"}, with ${Math.round(meetingOrExceeding)}% of reviewed employees meeting or exceeding expectations${amlLine}.`
    )
  }

  /** Action-oriented recommendations, as distinct from buildInsights()'s
   *  "what happened" findings — same rule-based approach (see this module's
   *  doc comment on why these aren't LLM-generated), driven by the
   *  configurable thresholds in REPORT_TARGETS. Explicitly NOT labeled
   *  "AI-generated" in the rendered report — that would misrepresent how
   *  they're produced — but called out as auto-generated from business
   *  rules, which is what the spec actually asks for when AI isn't wired up. */
  private buildRecommendations(bundle: ExportBundle): string[] {
    const recommendations: string[] = []

    const lowFillDepartments = bundle.positionFillRate.byDepartment.filter((d) => d.fillRate < REPORT_TARGETS.positionFillRatePercent)
    if (lowFillDepartments.length > 0) {
      const names = lowFillDepartments
        .slice(0, 3)
        .map((d) => d.name)
        .join(", ")
      recommendations.push(`Prioritize recruitment in departments with low position fill rates (below ${REPORT_TARGETS.positionFillRatePercent}%): ${names}.`)
    }

    if (bundle.leaveUtilization.utilizationPercent < REPORT_TARGETS.leaveUtilizationPercent) {
      recommendations.push(
        `Encourage employees to utilize their annual leave — utilization is at ${bundle.leaveUtilization.utilizationPercent}%, below the ${REPORT_TARGETS.leaveUtilizationPercent}% organizational target.`
      )
    }

    if (bundle.learning.amlCompletionRate !== null && bundle.learning.amlCompletionRate < REPORT_TARGETS.amlCompliancePercent) {
      recommendations.push(
        `Increase mandatory AML training participation — completion is at ${bundle.learning.amlCompletionRate}%, below the ${REPORT_TARGETS.amlCompliancePercent}% compliance target.`
      )
    }

    if (bundle.attritionRate.rate > REPORT_TARGETS.attritionWatchPercent) {
      recommendations.push(
        `Attrition is at ${bundle.attritionRate.rate}%, above the ${REPORT_TARGETS.attritionWatchPercent}% watch threshold — worth a targeted retention review in the departments driving it.`
      )
    }

    if (recommendations.length === 0) {
      recommendations.push("No metric is currently outside its target threshold for the selected filters.")
    }

    return recommendations
  }

  /** Same idea as buildRecommendations() above, but gated per-section so it
   *  only reasons about data the Custom Report Builder's selection actually
   *  included — see buildCustomInsights() for the equivalent pattern on the
   *  findings side. */
  private buildCustomRecommendations(bundle: CustomReportBundle): string[] {
    const recommendations: string[] = []

    if (bundle.positions) {
      const low = bundle.positions.byDepartment.filter((d) => Number(d.fillRate) < REPORT_TARGETS.positionFillRatePercent)
      if (low.length > 0) {
        const names = low
          .slice(0, 3)
          .map((d) => String(d.name))
          .join(", ")
        recommendations.push(`Prioritize recruitment in departments with low position fill rates (below ${REPORT_TARGETS.positionFillRatePercent}%): ${names}.`)
      }
    }

    if (bundle.leave && bundle.leave.utilization.utilizationPercent < REPORT_TARGETS.leaveUtilizationPercent) {
      recommendations.push(
        `Encourage employees to utilize their annual leave — utilization is at ${bundle.leave.utilization.utilizationPercent}%, below the ${REPORT_TARGETS.leaveUtilizationPercent}% target.`
      )
    }

    if (bundle.learning && bundle.learning.amlCompletionRate !== null && bundle.learning.amlCompletionRate < REPORT_TARGETS.amlCompliancePercent) {
      recommendations.push(
        `Increase mandatory AML training participation — completion is at ${bundle.learning.amlCompletionRate}%, below the ${REPORT_TARGETS.amlCompliancePercent}% target.`
      )
    }

    if (bundle.turnover && bundle.turnover.rate > REPORT_TARGETS.attritionWatchPercent) {
      recommendations.push(
        `Attrition is at ${bundle.turnover.rate}%, above the ${REPORT_TARGETS.attritionWatchPercent}% watch threshold — worth a targeted retention review.`
      )
    }

    return recommendations
  }

  private async buildBundle(filters: HrAnalyticsFilters): Promise<ExportBundle> {
    const [totalStaff, averageAge, bandDistribution, attritionRate, positionFillRate, leaveUtilization, employeeDistribution, exitSummary, demographics, performanceDistribution, learning] =
      await Promise.all([
        this.hrAnalyticsService.totalStaff(filters),
        this.hrAnalyticsService.averageAge(filters),
        this.hrAnalyticsService.bandDistribution(filters),
        this.hrAnalyticsService.attritionRate(filters),
        this.hrAnalyticsService.positionFillRate(filters),
        this.hrAnalyticsService.leaveUtilizationSummary(filters),
        this.hrAnalyticsService.employeeDistributionByDepartment(filters),
        this.hrAnalyticsService.exitSummary(filters),
        this.hrAnalyticsService.employeeDemographics(filters),
        this.delegated.performanceDistribution(filters),
        this.delegated.learningAnalyticsFor(filters),
      ])

    return { totalStaff, averageAge, bandDistribution, attritionRate, positionFillRate, leaveUtilization, employeeDistribution, exitSummary, demographics, performanceDistribution, learning }
  }

  /** Rule-based summary lines — NOT the AI-generated insights the spec
   *  flags as a Future Enhancement (see hr-analytics.module.ts's doc
   *  comment). Simple threshold/ranking logic over numbers already computed
   *  above, same spirit as the spec's own examples but without an LLM. */
  private buildInsights(bundle: ExportBundle): string[] {
    const insights: string[] = []

    if (bundle.attritionRate.breakdown.byDepartment[0]) {
      const top = bundle.attritionRate.breakdown.byDepartment[0]
      insights.push(`${top.label} has the highest number of exits this period (${top.count}).`)
    }
    if (bundle.positionFillRate.byDepartment.some((d) => d.fillRate < 80)) {
      const worst = [...bundle.positionFillRate.byDepartment].sort((a, b) => a.fillRate - b.fillRate)[0]
      insights.push(`${worst.name} has the lowest position fill rate at ${worst.fillRate}% (${worst.filled}/${worst.total} filled).`)
    }
    if (bundle.learning.amlCompletionRate !== null && bundle.learning.amlCompletionRate < 100) {
      insights.push(`AML training completion is at ${bundle.learning.amlCompletionRate}%, below full compliance.`)
    }
    if (bundle.attritionRate.changePercent !== 0) {
      const direction = bundle.attritionRate.changePercent > 0 ? "increased" : "decreased"
      insights.push(`Attrition has ${direction} by ${Math.abs(bundle.attritionRate.changePercent)} percentage points compared to last year.`)
    }
    if (insights.length === 0) insights.push("No notable outliers detected in the current filter selection.")

    return insights
  }

  // ==== Excel ================================================================

  async generateExcel(filters: HrAnalyticsFilters, actingEmployeeId?: string): Promise<Buffer> {
    const [bundle, cover] = await Promise.all([this.buildBundle(filters), this.buildCoverInfo(filters, actingEmployeeId)])
    const workbook = XLSX.utils.book_new()

    const summarySheet = XLSX.utils.aoa_to_sheet([
      [cover.reportTitle],
      [cover.periodLabel],
      ...(cover.departmentLabel ? [[`Department: ${cover.departmentLabel}`]] : []),
      [`Generated ${cover.generatedAtLabel} by ${cover.generatedByLabel}`],
      [],
      ["Executive Summary"],
      [this.buildExecutiveSummary(bundle)],
      [],
      ["Total Active Staff", bundle.totalStaff.activeCount],
      ["New Joiners (period)", bundle.totalStaff.newJoined],
      ["Exits (period)", bundle.totalStaff.exited],
      ["Change vs Last Year", bundle.totalStaff.changePercent !== null ? `${bundle.totalStaff.changePercent}%` : "N/A"],
      ["Average Age", bundle.averageAge.overall ?? "N/A"],
      ["Attrition Rate", `${bundle.attritionRate.rate}%`],
      ["Position Fill Rate", `${bundle.positionFillRate.fillRate}% (${bundle.positionFillRate.filled}/${bundle.positionFillRate.total})`],
      ["Leave Utilization", `${bundle.leaveUtilization.utilizationPercent}%`],
    ])
    XLSX.utils.book_append_sheet(workbook, summarySheet, "Summary")

    const bandSheet = XLSX.utils.json_to_sheet(bundle.bandDistribution.map((b) => ({ Band: b.bandName, Count: b.count, "Percent": b.percent })))
    XLSX.utils.book_append_sheet(workbook, bandSheet, "Band Distribution")

    const deptSheet = XLSX.utils.json_to_sheet(bundle.employeeDistribution.map((d) => ({ Department: d.departmentName, Count: d.count, "Percent": d.percent })))
    XLSX.utils.book_append_sheet(workbook, deptSheet, "By Department")

    const exitSheet = XLSX.utils.json_to_sheet(bundle.exitSummary.byReason.map((r) => ({ "Exit Reason": r.label, Count: r.count })))
    XLSX.utils.book_append_sheet(workbook, exitSheet, "Exits by Reason")

    const exitTrendSheet = XLSX.utils.json_to_sheet(bundle.exitSummary.trend.map((t) => ({ Year: t.year, Exits: t.exits })))
    XLSX.utils.book_append_sheet(workbook, exitTrendSheet, "Exit Trend")

    const ageSheet = XLSX.utils.json_to_sheet(bundle.demographics.ageHistogram.map((a) => ({ "Age Bracket": a.bucket, Count: a.count })))
    XLSX.utils.book_append_sheet(workbook, ageSheet, "Age Distribution")

    const perfSheet = XLSX.utils.json_to_sheet(bundle.performanceDistribution.map((p: { label: string; count: number; actualPercentage: number }) => ({ Rating: p.label, Count: p.count, Percent: p.actualPercentage })))
    XLSX.utils.book_append_sheet(workbook, perfSheet, "Performance Distribution")

    const recommendationsSheet = XLSX.utils.aoa_to_sheet([
      ["Recommendations"],
      ["Auto-generated from configurable business-rule thresholds — review before circulating."],
      [],
      ...this.buildRecommendations(bundle).map((line) => [line]),
    ])
    XLSX.utils.book_append_sheet(workbook, recommendationsSheet, "Recommendations")

    return XLSX.write(workbook, { type: "buffer", bookType: "xlsx" }) as Buffer
  }

  // ==== CSV (flat KPI summary — CSV has no multi-sheet concept) ====================

  async generateCsv(filters: HrAnalyticsFilters, actingEmployeeId?: string): Promise<string> {
    const [bundle, cover] = await Promise.all([this.buildBundle(filters), this.buildCoverInfo(filters, actingEmployeeId)])
    const rows: [string, string | number][] = [
      ["Report Period", cover.periodLabel],
      ...(cover.departmentLabel ? ([["Department", cover.departmentLabel]] as [string, string][]) : []),
      ["Generated", `${cover.generatedAtLabel} by ${cover.generatedByLabel}`],
      ["Total Active Staff", bundle.totalStaff.activeCount],
      ["New Joiners (period)", bundle.totalStaff.newJoined],
      ["Exits (period)", bundle.totalStaff.exited],
      ["Average Age", bundle.averageAge.overall ?? ""],
      ["Attrition Rate (%)", bundle.attritionRate.rate],
      ["Position Fill Rate (%)", bundle.positionFillRate.fillRate],
      ["Leave Utilization (%)", bundle.leaveUtilization.utilizationPercent],
      ...bundle.bandDistribution.map((b) => [`Band: ${b.bandName}`, b.count] as [string, number]),
      ...bundle.employeeDistribution.map((d) => [`Department: ${d.departmentName}`, d.count] as [string, number]),
    ]

    const escape = (value: string | number) => {
      const str = String(value)
      return /[",\n]/.test(str) ? `"${str.replaceAll('"', '""')}"` : str
    }
    return ["Metric,Value", ...rows.map(([k, v]) => `${escape(k)},${escape(v)}`)].join("\n")
  }

  // ==== PDF ================================================================

  async generatePdf(filters: HrAnalyticsFilters, actingEmployeeId?: string): Promise<Buffer> {
    const [bundle, cover] = await Promise.all([this.buildBundle(filters), this.buildCoverInfo(filters, actingEmployeeId)])
    const doc = new PDFDocument({ margin: 50, size: "A4" })
    const chunks: Buffer[] = []
    doc.on("data", (chunk: Buffer) => chunks.push(chunk))
    const done = new Promise<Buffer>((resolve) => doc.on("end", () => resolve(Buffer.concat(chunks))))

    this.renderCoverPage(doc, cover)

    doc.fontSize(14).fillColor(REPORT_THEME.colors.navy).font("Helvetica-Bold").text("Executive Summary")
    doc.moveDown(0.4)
    doc.fontSize(11).fillColor(REPORT_THEME.colors.text).font("Helvetica").text(this.buildExecutiveSummary(bundle))
    doc.fillColor("black").moveDown()

    this.section(doc, "Total Staff", [
      ["Active employees", bundle.totalStaff.activeCount],
      ["New joiners (period)", bundle.totalStaff.newJoined],
      ["Exits (period)", bundle.totalStaff.exited],
      ["Change vs last year", bundle.totalStaff.changePercent !== null ? `${bundle.totalStaff.changePercent}%` : "N/A"],
    ])

    this.section(doc, "Average Age", [["Organization average", bundle.averageAge.overall ?? "N/A"]])

    this.section(
      doc,
      "Band Distribution",
      bundle.bandDistribution.map((b) => [b.bandName, `${b.count} (${b.percent}%)`])
    )

    this.section(doc, "Attrition Rate", [
      ["Current rate", `${bundle.attritionRate.rate}%`],
      ["Previous year", `${bundle.attritionRate.previousYearRate}%`],
      ["Exits this period", bundle.attritionRate.exits],
    ])

    this.section(doc, "Position Fill Rate", [
      ["Fill rate", `${bundle.positionFillRate.fillRate}%`],
      ["Filled / Total", `${bundle.positionFillRate.filled} / ${bundle.positionFillRate.total}`],
    ])

    this.section(doc, "Leave Utilization", [
      ["Utilization", `${bundle.leaveUtilization.utilizationPercent}%`],
      ["Total entitlement (days)", bundle.leaveUtilization.totalEntitlement],
      ["Total taken (days)", bundle.leaveUtilization.totalTaken],
    ])

    this.section(
      doc,
      "Exit Summary",
      bundle.exitSummary.byReason.map((r) => [r.label, r.count])
    )

    doc.addPage()
    doc.fontSize(14).fillColor(REPORT_THEME.colors.navy).font("Helvetica-Bold").text("Key HR Insights")
    doc.font("Helvetica").moveDown(0.5)
    for (const insight of this.buildInsights(bundle)) {
      doc.fontSize(10).fillColor("#333333").text(`• ${insight}`)
      doc.moveDown(0.3)
    }

    doc.moveDown()
    doc.fontSize(14).fillColor(REPORT_THEME.colors.navy).font("Helvetica-Bold").text("Recommendations")
    doc.fontSize(8).fillColor(REPORT_THEME.colors.mutedLight).font("Helvetica").text("Auto-generated from configurable business-rule thresholds — review before circulating.")
    doc.moveDown(0.4)
    for (const recommendation of this.buildRecommendations(bundle)) {
      doc.fontSize(10).fillColor(REPORT_THEME.colors.text).text(`• ${recommendation}`)
      doc.moveDown(0.3)
    }

    doc.end()
    return done
  }

  /** First page of every PDF export — logo (or a text wordmark fallback
   *  when the asset isn't present, see resolveLogoPath()), title, report
   *  period, filtered department (if any), and who/when it was generated.
   *  Ends on doc.addPage() so callers can start their own content on a
   *  clean second page without needing to know this drew anything. */
  private renderCoverPage(doc: PDFKit.PDFDocument, cover: ReportCoverInfo) {
    const left = doc.page.margins.left
    doc.rect(0, 0, doc.page.width, 8).fill(REPORT_THEME.colors.gold)
    doc.fillColor("black")

    let cursorY = 70
    const logoPath = resolveLogoPath()
    if (logoPath) {
      doc.image(logoPath, left, cursorY, { width: 130 })
      cursorY += 80
    } else {
      doc.roundedRect(left, cursorY, 130, 48, 6).fill(REPORT_THEME.colors.navy)
      doc.fillColor("white").fontSize(18).font("Helvetica-Bold").text("NCBA", left, cursorY + 14, { width: 130, align: "center" })
      cursorY += 68
    }

    doc.fillColor(REPORT_THEME.colors.muted).fontSize(10).font("Helvetica").text("PEOPLE & CULTURE · WORKFORCE SNAPSHOT", left, cursorY)
    cursorY += 22
    doc.fillColor(REPORT_THEME.colors.navy).fontSize(26).font("Helvetica-Bold").text(cover.reportTitle, left, cursorY)
    cursorY += 42
    doc.fillColor(REPORT_THEME.colors.muted).fontSize(13).font("Helvetica").text(cover.periodLabel, left, cursorY)
    cursorY += 24

    if (cover.departmentLabel) {
      doc.text(`Department: ${cover.departmentLabel}`, left, cursorY)
      cursorY += 22
    }

    cursorY += 12
    doc.fontSize(10).fillColor(REPORT_THEME.colors.mutedLight)
    doc.text(`Date generated: ${cover.generatedAtLabel}`, left, cursorY)
    cursorY += 16
    doc.text(`Generated by: ${cover.generatedByLabel}`, left, cursorY)
    cursorY += 16
    doc.text("Prepared by NCBA Rwanda PeopleSuite", left, cursorY)
    doc.text("CONFIDENTIAL — INTERNAL USE ONLY", left, doc.page.height - doc.page.margins.bottom - 20)

    doc.fillColor("black").font("Helvetica")
    doc.addPage()
  }

  private section(doc: PDFKit.PDFDocument, title: string, rows: [string, string | number][]) {
    doc.fontSize(13).fillColor("black").text(title, { underline: true })
    doc.moveDown(0.3)
    for (const [label, value] of rows) {
      doc.fontSize(10).fillColor("#555555").text(label, { continued: true, width: 250 })
      doc.fillColor("black").text(`  ${value}`)
    }
    doc.moveDown()
  }

  // ==== PowerPoint =============================================================

  /** Executive presentation: KPI summary, charts (native PowerPoint charts,
   *  not images), workforce trends, performance/leave/recruitment/learning
   *  sections, and key HR insights — matching the spec's content list. */
  async generatePptx(filters: HrAnalyticsFilters, actingEmployeeId: string): Promise<Buffer> {
    const [bundle, cover, hiringExitTrend, ratingsByDepartment] = await Promise.all([
      this.buildBundle(filters),
      this.buildCoverInfo(filters, actingEmployeeId),
      this.hrAnalyticsService.hiringExitTrend(filters),
      this.delegated.performanceByDepartment(filters),
    ])
    const recruitment = await this.delegated.recruitmentAnalyticsFor(actingEmployeeId)

    const pptx = new PptxGenJS()
    pptx.defineLayout({ name: "A4", width: 10, height: 7.5 })
    pptx.layout = "A4"

    this.addCoverSlide(pptx, cover)

    const summarySlide = pptx.addSlide()
    summarySlide.addText("Executive Summary", { x: 0.4, y: 0.3, fontSize: 22, bold: true, color: "0A2647" })
    summarySlide.addText(this.buildExecutiveSummary(bundle), { x: 0.5, y: 1.1, w: 9, h: 5.5, fontSize: 15, color: "333333", valign: "top" })

    // ---- Key Metrics — 6 KPI cards, same layout/colors/breakdowns as the
    // dashboard's KpiCards component (client/app/admin/hr-analytics/kpi-cards.tsx)
    // rather than the old plain metric/value table.
    this.addKeyMetricsSlide(pptx, bundle)

    // ---- Charts & Trends — same chart set, colors, and pairing as the
    // dashboard's charts.tsx, using pptxgenjs's native chart types so these
    // stay real, editable PowerPoint charts (not embedded images).
    const deptSlide = pptx.addSlide()
    deptSlide.addText("Employee Distribution by Department", { x: 0.4, y: 0.3, fontSize: 22, bold: true, color: "0A2647" })
    const deptSorted = [...bundle.employeeDistribution].sort((a, b) => b.count - a.count)
    deptSlide.addChart(
      pptx.ChartType.bar,
      [{ name: "Employees", labels: deptSorted.map((d) => d.departmentName), values: deptSorted.map((d) => d.count) }],
      { x: 0.5, y: 1.0, w: 9, h: 5.8, barDir: "bar", chartColors: CHART_PALETTE, showLegend: false, catAxisLabelFontSize: 10, valAxisLabelFontSize: 10 }
    )

    const fillRateSlide = pptx.addSlide()
    fillRateSlide.addText("Position Fill Rate by Department", { x: 0.4, y: 0.3, fontSize: 22, bold: true, color: "0A2647" })
    const fillSorted = [...bundle.positionFillRate.byDepartment].sort((a, b) => a.fillRate - b.fillRate)
    fillRateSlide.addChart(
      pptx.ChartType.bar,
      [{ name: "Fill Rate", labels: fillSorted.map((d) => d.name), values: fillSorted.map((d) => d.fillRate) }],
      {
        x: 0.5,
        y: 1.0,
        w: 9,
        h: 5.8,
        barDir: "bar",
        chartColors: fillSorted.map((d) => fillRateColor(d.fillRate)),
        showLegend: false,
        catAxisLabelFontSize: 10,
        valAxisLabelFontSize: 10,
        valAxisMaxVal: 100,
      }
    )

    const bandSlide = pptx.addSlide()
    bandSlide.addText("Band Distribution", { x: 0.4, y: 0.3, fontSize: 22, bold: true, color: "0A2647" })
    bandSlide.addChart(
      pptx.ChartType.bar,
      [{ name: "Employees", labels: bundle.bandDistribution.map((b) => b.bandName), values: bundle.bandDistribution.map((b) => b.count) }],
      { x: 0.5, y: 1.0, w: 9, h: 5.8, barDir: "bar", chartColors: CHART_PALETTE, showLegend: false, catAxisLabelFontSize: 10, valAxisLabelFontSize: 10 }
    )

    // ---- Additional demographic breakdowns already computed in the bundle
    // (employeeDemographics()) but previously only surfaced as tiny KPI-card
    // mini-visualizations or not at all — given their own full-size slides
    // per the "bring more charts where applicable" request.
    const genderSlide = pptx.addSlide()
    genderSlide.addText("Gender Distribution", { x: 0.4, y: 0.3, fontSize: 22, bold: true, color: "0A2647" })
    const genderColorFor = (key: string) => (key === "MALE" ? "0A2647" : key === "FEMALE" ? "D4537E" : "B8860B")
    genderSlide.addChart(
      pptx.ChartType.doughnut,
      [{ name: "Employees", labels: bundle.demographics.genderDistribution.map((g) => g.label), values: bundle.demographics.genderDistribution.map((g) => g.count) }],
      {
        x: 2.5,
        y: 1.0,
        w: 5,
        h: 5.5,
        chartColors: bundle.demographics.genderDistribution.map((g) => genderColorFor(g.key)),
        showLegend: true,
        legendPos: "b",
        showPercent: true,
        dataBorder: { pt: 1, color: "FFFFFF" },
        holeSize: 55,
      }
    )

    const contractTypeSlide = pptx.addSlide()
    contractTypeSlide.addText("Contract Type Distribution", { x: 0.4, y: 0.3, fontSize: 22, bold: true, color: "0A2647" })
    contractTypeSlide.addChart(
      pptx.ChartType.bar,
      [
        {
          name: "Employees",
          labels: bundle.demographics.contractTypeDistribution.map((c) => c.label),
          values: bundle.demographics.contractTypeDistribution.map((c) => c.count),
        },
      ],
      { x: 0.5, y: 1.0, w: 9, h: 5.8, barDir: "bar", chartColors: CHART_PALETTE, showLegend: false, catAxisLabelFontSize: 10, valAxisLabelFontSize: 10 }
    )

    const ageSlide = pptx.addSlide()
    ageSlide.addText("Age Distribution", { x: 0.4, y: 0.3, fontSize: 22, bold: true, color: "0A2647" })
    ageSlide.addChart(
      pptx.ChartType.bar,
      [{ name: "Employees", labels: bundle.demographics.ageHistogram.map((a) => a.bucket), values: bundle.demographics.ageHistogram.map((a) => a.count) }],
      { x: 0.5, y: 1.0, w: 9, h: 5.8, chartColors: ["7F77DD"], showLegend: false, catAxisLabelFontSize: 11, valAxisLabelFontSize: 10 }
    )

    const trendSlide = pptx.addSlide()
    trendSlide.addText("Hiring vs. Exit Trend", { x: 0.4, y: 0.3, fontSize: 22, bold: true, color: "0A2647" })
    // Line, not area — two overlapping semi-transparent area fills render as
    // a muddy blend in PowerPoint/LibreOffice (no per-series gradient fade
    // like the dashboard's SVG version), where distinct lines stay crisp.
    trendSlide.addChart(
      pptx.ChartType.line,
      [
        { name: "Hires", labels: hiringExitTrend.map((t) => String(t.year)), values: hiringExitTrend.map((t) => t.hires) },
        { name: "Exits", labels: hiringExitTrend.map((t) => String(t.year)), values: hiringExitTrend.map((t) => t.exits) },
      ],
      {
        x: 0.5,
        y: 1.0,
        w: 9,
        h: 5.8,
        chartColors: ["5DCAA5", "D85A30"],
        lineSize: 2.5,
        lineDataSymbol: "circle",
        lineDataSymbolSize: 6,
        showLegend: true,
        legendPos: "b",
        catAxisLabelFontSize: 10,
        valAxisLabelFontSize: 10,
      }
    )

    const exitReasonsSlide = pptx.addSlide()
    exitReasonsSlide.addText("Exit Reasons", { x: 0.4, y: 0.3, fontSize: 22, bold: true, color: "0A2647" })
    const exitReasonsSorted = [...bundle.exitSummary.byReason].sort((a, b) => b.count - a.count)
    exitReasonsSlide.addChart(
      pptx.ChartType.bar,
      [{ name: "Exits", labels: exitReasonsSorted.map((r) => r.label), values: exitReasonsSorted.map((r) => r.count) }],
      { x: 0.5, y: 1.0, w: 9, h: 5.8, barDir: "bar", chartColors: ["D4537E"], showLegend: false, catAxisLabelFontSize: 10, valAxisLabelFontSize: 10 }
    )

    const perfDistSlide = pptx.addSlide()
    perfDistSlide.addText("Performance Distribution — Actual vs. Expected", { x: 0.4, y: 0.3, fontSize: 22, bold: true, color: "0A2647" })
    const perfRows = [...(bundle.performanceDistribution as { rank: number; label: string; actualPercentage: number; expectedPercentage: number | null }[])].sort((a, b) => a.rank - b.rank)
    perfDistSlide.addChart(
      pptx.ChartType.line,
      [
        { name: "Expected % (bell curve)", labels: perfRows.map((p) => p.label), values: perfRows.map((p) => p.expectedPercentage ?? 0) },
        { name: "Actual %", labels: perfRows.map((p) => p.label), values: perfRows.map((p) => p.actualPercentage) },
      ],
      {
        x: 0.5,
        y: 1.0,
        w: 9,
        h: 5.8,
        chartColors: ["B8860B", "0A2647"],
        lineSmooth: true,
        lineSize: 2.5,
        lineDataSymbol: "circle",
        lineDataSymbolSize: 6,
        showLegend: true,
        legendPos: "b",
        catAxisLabelFontSize: 10,
        valAxisLabelFontSize: 10,
      }
    )

    const ratingsSlide = pptx.addSlide()
    ratingsSlide.addText("Ratings by Department", { x: 0.4, y: 0.3, fontSize: 22, bold: true, color: "0A2647" })
    const ratingsSorted = [...ratingsByDepartment].sort((a: { averageRating: number }, b: { averageRating: number }) => b.averageRating - a.averageRating) as {
      departmentName: string
      averageRating: number
    }[]
    ratingsSlide.addChart(
      pptx.ChartType.bar,
      [{ name: "Avg. Rating", labels: ratingsSorted.map((r) => r.departmentName), values: ratingsSorted.map((r) => r.averageRating) }],
      { x: 0.5, y: 1.0, w: 9, h: 5.8, barDir: "bar", chartColors: ["B8860B"], showLegend: false, catAxisLabelFontSize: 10, valAxisLabelFontSize: 10, valAxisMaxVal: 5 }
    )

    // Leave & Recruitment & Learning — 3 KPI-style cards (same shell as Key
    // Metrics) instead of a plain metric/value table, so this slide matches
    // the rest of the deck's visual language rather than reverting to text.
    const leaveSlide = pptx.addSlide()
    leaveSlide.addText("Leave, Recruitment & Learning", { x: 0.4, y: 0.3, fontSize: 22, bold: true, color: "0A2647" })
    leaveSlide.addText("Snapshot across the three areas HR tracks outside core headcount.", { x: 0.4, y: 0.68, fontSize: 11, color: "666666" })

    const CARD3_W = 2.9333
    const CARD3_H = 3.4
    const CARD3_X = [0.4, 3.5333, 6.6667]

    {
      const body = this.addKpiShell(
        pptx,
        leaveSlide,
        { x: CARD3_X[0], y: 1.15, w: CARD3_W, h: CARD3_H },
        "0A2647",
        "Leave Utilization",
        `${bundle.leaveUtilization.utilizationPercent}%`,
        `${bundle.leaveUtilization.totalTaken} of ${bundle.leaveUtilization.totalEntitlement} days used`
      )
      this.addGaugeDonut(pptx, leaveSlide, body.x + body.w / 2 - 0.6, body.y + 0.1, 1.2, bundle.leaveUtilization.utilizationPercent, "0A2647")
      leaveSlide.addText(`On leave now: ${bundle.leaveUtilization.currentlyOnLeaveCount} employee${bundle.leaveUtilization.currentlyOnLeaveCount === 1 ? "" : "s"}`, {
        x: body.x,
        y: body.y + 1.5,
        w: body.w,
        h: 0.3,
        fontSize: 9,
        align: "center",
        color: "666666",
      })
    }

    {
      const body = this.addKpiShell(
        pptx,
        leaveSlide,
        { x: CARD3_X[1], y: 1.15, w: CARD3_W, h: CARD3_H },
        "5DCAA5",
        "Recruitment",
        String(recruitment.overview.openRequisitions),
        "Open requisitions"
      )
      const rows = [
        ["Time to hire", recruitment.timeToHire.averageDays !== null ? `${recruitment.timeToHire.averageDays} days` : "N/A"],
        ["Offer acceptance", recruitment.offerStats.acceptanceRate !== null ? `${recruitment.offerStats.acceptanceRate}%` : "N/A"],
      ]
      rows.forEach(([label, value], i) => {
        const rowY = body.y + 0.15 + i * 0.55
        leaveSlide.addText(label, { x: body.x, y: rowY, w: body.w, h: 0.22, fontSize: 8.5, color: "888888" })
        leaveSlide.addText(value, { x: body.x, y: rowY + 0.2, w: body.w, h: 0.3, fontSize: 15, bold: true, color: "1A1A1A" })
      })
    }

    {
      const body = this.addKpiShell(
        pptx,
        leaveSlide,
        { x: CARD3_X[2], y: 1.15, w: CARD3_W, h: CARD3_H },
        "B8860B",
        "Learning",
        `${bundle.learning.trainingCompletionRate}%`,
        "Training completion rate"
      )
      this.addGaugeDonut(pptx, leaveSlide, body.x + body.w / 2 - 0.6, body.y + 0.1, 1.2, bundle.learning.trainingCompletionRate, "B8860B")
      leaveSlide.addText(
        bundle.learning.amlCompletionRate === null ? "AML compliance: not tracked" : `AML compliance: ${bundle.learning.amlCompletionRate}%`,
        { x: body.x, y: body.y + 1.5, w: body.w, h: 0.3, fontSize: 9, align: "center", color: "666666" }
      )
    }

    const insightsSlide = pptx.addSlide()
    insightsSlide.addText("Key HR Insights", { x: 0.4, y: 0.3, fontSize: 22, bold: true, color: "0A2647" })
    insightsSlide.addText(
      this.buildInsights(bundle)
        .map((line) => ({ text: line, options: { bullet: true, breakLine: true } }))
        .flatMap((item) => [item]),
      { x: 0.5, y: 1.1, w: 9, h: 5, fontSize: 14, color: "333333", valign: "top" }
    )

    const recommendationsSlide = pptx.addSlide()
    recommendationsSlide.addText("Recommendations", { x: 0.4, y: 0.3, fontSize: 22, bold: true, color: "0A2647" })
    recommendationsSlide.addText("Auto-generated from configurable business-rule thresholds — review before circulating.", {
      x: 0.4,
      y: 0.85,
      w: 9,
      fontSize: 10,
      italic: true,
      color: "888888",
    })
    recommendationsSlide.addText(
      this.buildRecommendations(bundle).map((line) => ({ text: line, options: { bullet: true, breakLine: true } })),
      { x: 0.5, y: 1.3, w: 9, h: 4.8, fontSize: 14, color: "333333", valign: "top" }
    )

    const output = await pptx.write({ outputType: "nodebuffer" })
    return output as Buffer
  }

  /** Rounded card shell (border, colored accent strip, icon dot, label,
   *  headline value, subtitle) shared by every Key Metrics card — mirrors
   *  KpiShell in the dashboard's kpi-cards.tsx. Callers draw whatever
   *  card-specific mid-section content they need (segmented bar, mini bars,
   *  gauge, etc.) into the returned body box, then optionally addPill(). */
  private addKpiShell(
    pptx: PptxGenJS,
    slide: PptxGenJS.Slide,
    box: { x: number; y: number; w: number; h: number },
    accentHex: string,
    label: string,
    value: string,
    subtitle: string
  ): { x: number; y: number; w: number; h: number } {
    const { x, y, w, h } = box
    slide.addShape(pptx.ShapeType.roundRect, { x, y, w, h, rectRadius: 0.06, fill: { color: "FFFFFF" }, line: { color: "E5E7EB", width: 0.75 } })
    slide.addShape(pptx.ShapeType.rect, { x: x + 0.02, y, w: w - 0.04, h: 0.05, fill: { color: accentHex } })
    slide.addText(label.toUpperCase(), { x: x + 0.15, y: y + 0.14, w: w - 0.65, h: 0.22, fontSize: 8.5, bold: true, color: "666666", charSpacing: 1 })
    slide.addShape(pptx.ShapeType.ellipse, { x: x + w - 0.48, y: y + 0.12, w: 0.3, h: 0.3, fill: { color: accentHex, transparency: 82 }, line: { type: "none" } })
    slide.addText(value, { x: x + 0.15, y: y + 0.42, w: w - 0.3, h: 0.46, fontSize: 21, bold: true, color: "1A1A1A" })
    slide.addText(subtitle, { x: x + 0.15, y: y + 0.88, w: w - 0.3, h: 0.3, fontSize: 8, color: "666666" })
    return { x: x + 0.15, y: y + 1.22, w: w - 0.3, h: h - 1.55 }
  }

  /** Status pill at the bottom of a card — mirrors attritionPill()/
   *  fillRatePill()/leaveUtilizationPill() in kpi-cards.tsx (same three
   *  tones, same thresholds are applied by the caller before calling this). */
  private addPill(pptx: PptxGenJS, slide: PptxGenJS.Slide, box: { x: number; y: number; w: number }, tone: "good" | "warn" | "bad", text: string) {
    const tones = {
      good: { bg: "5DCAA5", text: "2F6E56" },
      warn: { bg: "B8860B", text: "6B4E06" },
      bad: { bg: "D4537E", text: "8A2C46" },
    }[tone]
    slide.addShape(pptx.ShapeType.roundRect, { x: box.x, y: box.y, w: box.w, h: 0.3, rectRadius: 0.05, fill: { color: tones.bg, transparency: 82 }, line: { type: "none" } })
    slide.addText(text, { x: box.x, y: box.y, w: box.w, h: 0.3, fontSize: 8, bold: true, align: "center", valign: "middle", color: tones.text })
  }

  /** Small ring "gauge" for the two percent-of-a-whole cards (Fill Rate,
   *  Leave Utilization) — a native doughnut chart standing in for the
   *  dashboard's hand-drawn SVG radial gauge, with the percentage overlaid
   *  as plain text since pptxgenjs doughnut charts don't support a center
   *  label natively. */
  private addGaugeDonut(pptx: PptxGenJS, slide: PptxGenJS.Slide, x: number, y: number, size: number, percent: number, colorHex: string) {
    slide.addChart(pptx.ChartType.doughnut, [{ name: "Value", labels: ["Filled", "Remaining"], values: [percent, Math.max(0, 100 - percent)] }], {
      x,
      y,
      w: size,
      h: size,
      chartColors: [colorHex, "EDEDED"],
      showLegend: false,
      showTitle: false,
      showValue: false,
      showPercent: false,
      dataBorder: { pt: 1, color: "FFFFFF" },
      holeSize: 68,
    })
    slide.addText(`${Math.round(percent)}%`, { x, y: y + size / 2 - 0.15, w: size, h: 0.3, fontSize: 11, bold: true, align: "center", color: "1A1A1A" })
  }

  /** "Key Metrics" slide — 6 KPI cards in a 2x3 grid reproducing the
   *  dashboard's KpiCards component (client/app/admin/hr-analytics/kpi-cards.tsx):
   *  same 6 metrics, same accent colors, same per-card mini-visualization and
   *  status pill, so the exported deck reads as a direct snapshot of what's
   *  on screen instead of a plain metric/value table. */
  private addKeyMetricsSlide(pptx: PptxGenJS, bundle: ExportBundle) {
    const slide = pptx.addSlide()
    slide.addText("Key Metrics", { x: 0.4, y: 0.3, fontSize: 22, bold: true, color: "0A2647" })
    slide.addText("Headline workforce numbers for the selected filters.", { x: 0.4, y: 0.68, fontSize: 11, color: "666666" })

    const CARD_W = 2.9333
    const CARD_H = 3.0
    const COLS_X = [0.4, 3.5333, 6.6667]
    const ROWS_Y = [1.05, 4.15]
    const box = (index: number) => ({ x: COLS_X[index % 3], y: ROWS_Y[Math.floor(index / 3)], w: CARD_W, h: CARD_H })

    const notActive = bundle.totalStaff.exited
    const totalHeadcount = bundle.totalStaff.activeCount + notActive
    const male = bundle.demographics.genderDistribution.find((g) => g.key === "MALE")?.count ?? 0
    const female = bundle.demographics.genderDistribution.find((g) => g.key === "FEMALE")?.count ?? 0

    // Card 1 — Staff Headcount (gold)
    {
      const body = this.addKpiShell(pptx, slide, box(0), "B8860B", "Staff Headcount", totalHeadcount.toLocaleString(), `${bundle.totalStaff.activeCount} active · ${notActive} not active`)
      const total = male + female || 1
      const maleW = body.w * (male / total)
      slide.addShape(pptx.ShapeType.rect, { x: body.x, y: body.y, w: maleW, h: 0.14, fill: { color: "0A2647" }, line: { type: "none" } })
      slide.addShape(pptx.ShapeType.rect, { x: body.x + maleW, y: body.y, w: Math.max(0, body.w - maleW), h: 0.14, fill: { color: "D4537E" }, line: { type: "none" } })
      slide.addText(`♂ ${male} male`, { x: body.x, y: body.y + 0.24, w: body.w / 2, h: 0.25, fontSize: 8.5, color: "666666" })
      slide.addText(`♀ ${female} female`, { x: body.x + body.w / 2, y: body.y + 0.24, w: body.w / 2, h: 0.25, fontSize: 8.5, color: "666666", align: "right" })
    }

    // Card 2 — Average Age (purple)
    {
      const ageHistogram = bundle.demographics.ageHistogram
      const body = this.addKpiShell(
        pptx,
        slide,
        box(1),
        "7F77DD",
        "Average Age",
        bundle.averageAge.overall !== null ? `${bundle.averageAge.overall} yrs` : "—",
        `Across ${bundle.averageAge.byDepartment.length} department${bundle.averageAge.byDepartment.length === 1 ? "" : "s"}`
      )
      const maxCount = Math.max(1, ...ageHistogram.map((a) => a.count))
      const slotW = body.w / Math.max(1, ageHistogram.length)
      const maxBarH = 0.45
      ageHistogram.forEach((bucket, i) => {
        const barH = bucket.count === 0 ? 0 : 0.06 + (bucket.count / maxCount) * (maxBarH - 0.06)
        const slotX = body.x + i * slotW
        slide.addText(String(bucket.count), { x: slotX, y: body.y, w: slotW, h: 0.2, fontSize: 9, bold: true, align: "center", color: "1A1A1A" })
        slide.addShape(pptx.ShapeType.rect, {
          x: slotX + slotW * 0.3,
          y: body.y + 0.22 + (maxBarH - barH),
          w: slotW * 0.4,
          h: Math.max(0.02, barH),
          fill: { color: "7F77DD" },
          line: { type: "none" },
        })
        slide.addText(bucket.bucket, { x: slotX, y: body.y + 0.22 + maxBarH + 0.04, w: slotW, h: 0.3, fontSize: 6.5, align: "center", color: "666666" })
      })
    }

    // Card 3 — Band Distribution (mint)
    {
      const bandTotal = bundle.bandDistribution.reduce((sum, b) => sum + b.count, 0)
      const topBands = [...bundle.bandDistribution].sort((a, b) => b.count - a.count).slice(0, 4)
      const body = this.addKpiShell(pptx, slide, box(2), "5DCAA5", "Band Distribution", bandTotal.toLocaleString(), "Employees with a band assigned")
      const labelW = 0.85
      const pctW = 0.4
      const barW = body.w - labelW - pctW
      topBands.forEach((band, i) => {
        const rowY = body.y + i * 0.3
        slide.addText(band.bandName, { x: body.x, y: rowY, w: labelW, h: 0.22, fontSize: 7.5, color: "666666" })
        slide.addShape(pptx.ShapeType.roundRect, { x: body.x + labelW, y: rowY + 0.16, w: barW, h: 0.08, rectRadius: 0.04, fill: { color: "E5E7EB" }, line: { type: "none" } })
        slide.addShape(pptx.ShapeType.roundRect, {
          x: body.x + labelW,
          y: rowY + 0.16,
          w: Math.max(0.04, barW * (band.percent / 100)),
          h: 0.08,
          rectRadius: 0.04,
          fill: { color: "5DCAA5" },
          line: { type: "none" },
        })
        slide.addText(`${band.percent}%`, { x: body.x + labelW + barW, y: rowY, w: pctW, h: 0.22, fontSize: 7.5, align: "right", color: "666666" })
      })
    }

    // Card 4 — Attrition Rate (pink)
    {
      const retainedPercent = Math.max(0, Math.round((100 - bundle.attritionRate.rate) * 10) / 10)
      const voluntaryExits = bundle.exitSummary.byReason.find((r) => r.key === "RESIGNATION")?.count ?? 0
      const body = this.addKpiShell(
        pptx,
        slide,
        box(3),
        "D4537E",
        "Attrition Rate",
        `${bundle.attritionRate.rate}%`,
        `${bundle.attritionRate.exits} exits · ${retainedPercent}% retained`
      )
      slide.addText("Voluntary exits", { x: body.x, y: body.y, w: body.w / 2, h: 0.2, fontSize: 8, color: "888888" })
      slide.addText(String(voluntaryExits), { x: body.x, y: body.y + 0.2, w: body.w / 2, h: 0.3, fontSize: 13, bold: true, color: "1A1A1A" })
      slide.addText("YoY change", { x: body.x + body.w / 2, y: body.y, w: body.w / 2, h: 0.2, fontSize: 8, color: "888888" })
      const yoy = bundle.attritionRate.changePercent
      slide.addText(`${yoy > 0 ? "+" : ""}${yoy}%`, {
        x: body.x + body.w / 2,
        y: body.y + 0.2,
        w: body.w / 2,
        h: 0.3,
        fontSize: 13,
        bold: true,
        color: yoy > 0 ? "D4537E" : "5DCAA5",
      })
      const rate = bundle.attritionRate.rate
      const pill = rate >= 15 ? ({ tone: "bad", text: "● High — review urgently" } as const) : rate >= 8 ? ({ tone: "warn", text: "● Moderate — monitor" } as const) : ({ tone: "good", text: "✓ Healthy attrition" } as const)
      this.addPill(pptx, slide, { x: body.x, y: body.y + body.h - 0.32, w: body.w }, pill.tone, pill.text)
    }

    // Card 5 — Fill Rate (orange)
    {
      const vacant = bundle.positionFillRate.total - bundle.positionFillRate.filled
      const body = this.addKpiShell(
        pptx,
        slide,
        box(4),
        "D85A30",
        "Fill Rate",
        `${bundle.positionFillRate.fillRate}%`,
        `${bundle.positionFillRate.filled} of ${bundle.positionFillRate.total} positions filled`
      )
      this.addGaugeDonut(pptx, slide, body.x, body.y, 1.1, bundle.positionFillRate.fillRate, "D85A30")
      slide.addText(`${bundle.positionFillRate.filled} filled`, { x: body.x + 1.2, y: body.y + 0.3, w: body.w - 1.2, h: 0.25, fontSize: 8.5, color: "666666" })
      slide.addText(`${vacant} vacant`, { x: body.x + 1.2, y: body.y + 0.6, w: body.w - 1.2, h: 0.25, fontSize: 8.5, color: "666666" })
      const fillRate = bundle.positionFillRate.fillRate
      const pill =
        fillRate < 50
          ? ({ tone: "bad", text: "● Critical vacancies" } as const)
          : fillRate < 75
            ? ({ tone: "warn", text: "● Some vacancies — plan hiring" } as const)
            : ({ tone: "good", text: "✓ Well staffed" } as const)
      this.addPill(pptx, slide, { x: body.x, y: body.y + body.h - 0.32, w: body.w }, pill.tone, pill.text)
    }

    // Card 6 — Leave Utilization (navy)
    {
      const body = this.addKpiShell(
        pptx,
        slide,
        box(5),
        "0A2647",
        "Leave Utilization",
        `${bundle.leaveUtilization.utilizationPercent}%`,
        `${bundle.leaveUtilization.totalTaken} of ${bundle.leaveUtilization.totalEntitlement} days used`
      )
      this.addGaugeDonut(pptx, slide, body.x, body.y, 1.1, bundle.leaveUtilization.utilizationPercent, "0A2647")
      slide.addText(`On leave now: ${bundle.leaveUtilization.currentlyOnLeaveCount}`, { x: body.x + 1.2, y: body.y + 0.4, w: body.w - 1.2, h: 0.4, fontSize: 8.5, color: "666666" })
      const utilization = bundle.leaveUtilization.utilizationPercent
      const pill =
        utilization >= 80
          ? ({ tone: "bad", text: "● High usage — check coverage" } as const)
          : utilization < 40
            ? ({ tone: "warn", text: "● Low usage — encourage leave" } as const)
            : ({ tone: "good", text: "✓ Healthy utilization" } as const)
      this.addPill(pptx, slide, { x: body.x, y: body.y + body.h - 0.32, w: body.w }, pill.tone, pill.text)
    }
  }

  /** Cover slide shared by generatePptx() and generateCustomPptx() —
   *  addImage() needs a real file on disk (unlike doc.image() above, which
   *  can accept a Buffer, pptxgenjs's image path option is the simplest
   *  route here since resolveLogoPath() already resolves to one), falling
   *  back to a drawn navy badge with "NCBA" text when the asset is missing. */
  private addCoverSlide(pptx: PptxGenJS, cover: ReportCoverInfo, title = cover.reportTitle) {
    const slide = pptx.addSlide()
    slide.background = { color: "FFFFFF" }
    slide.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: "100%", h: 0.12, fill: { color: REPORT_THEME.colors.gold } })

    const logoPath = resolveLogoPath()
    if (logoPath) {
      slide.addImage({ path: logoPath, x: 0.5, y: 0.6, w: 1.8, h: 0.7 })
    } else {
      slide.addShape(pptx.ShapeType.roundRect, { x: 0.5, y: 0.6, w: 1.6, h: 0.6, fill: { color: REPORT_THEME.colors.navy }, rectRadius: 0.08 })
      slide.addText("NCBA", { x: 0.5, y: 0.6, w: 1.6, h: 0.6, fontSize: 18, bold: true, color: "FFFFFF", align: "center", valign: "middle" })
    }

    slide.addText("PEOPLE & CULTURE · WORKFORCE SNAPSHOT", { x: 0.5, y: 2.3, w: 9, h: 0.35, fontSize: 11, color: REPORT_THEME.colors.muted })
    slide.addText(title, { x: 0.5, y: 2.65, w: 9, h: 0.9, fontSize: 30, bold: true, color: REPORT_THEME.colors.navy })
    slide.addText(cover.periodLabel, { x: 0.5, y: 3.6, w: 9, h: 0.4, fontSize: 15, color: REPORT_THEME.colors.muted })
    if (cover.departmentLabel) {
      slide.addText(`Department: ${cover.departmentLabel}`, { x: 0.5, y: 4.0, w: 9, h: 0.35, fontSize: 13, color: REPORT_THEME.colors.muted })
    }
    slide.addText(`Date generated: ${cover.generatedAtLabel}`, { x: 0.5, y: 6.5, w: 9, h: 0.3, fontSize: 10, color: REPORT_THEME.colors.mutedLight })
    slide.addText(`Generated by: ${cover.generatedByLabel}`, { x: 0.5, y: 6.8, w: 9, h: 0.3, fontSize: 10, color: REPORT_THEME.colors.mutedLight })
    slide.addText("Prepared by NCBA Rwanda PeopleSuite", { x: 0.5, y: 7.1, w: 9, h: 0.3, fontSize: 10, color: REPORT_THEME.colors.mutedLight })
  }

  // ==== Custom Report Builder ======================================================
  // Lets an admin pick which sections to include (each with its own optional
  // date-range override) rather than always exporting every fixed section
  // above — see REPORT_SECTIONS and hr-analytics-export.controller.ts's
  // `reports/custom` route.

  private mergeDateRange(base: HrAnalyticsFilters, override?: { dateFrom?: string; dateTo?: string }): HrAnalyticsFilters {
    if (!override || (!override.dateFrom && !override.dateTo)) return base
    // A section-level date range replaces the whole date dimension (not just
    // dateFrom/dateTo) so it can't be silently overridden by a leftover
    // years/year/month/quarter value from the dashboard's global filters —
    // see resolveDateRange()'s priority order in hr-analytics-filters.util.ts.
    return { ...base, dateFrom: override.dateFrom, dateTo: override.dateTo, years: undefined, year: undefined, month: undefined, quarter: undefined }
  }

  private async buildCustomBundle(sections: CustomReportSectionInput[], baseFilters: HrAnalyticsFilters): Promise<CustomReportBundle> {
    const selected = new Map(sections.filter((s) => REPORT_SECTION_KEYS.has(s.key)).map((s) => [s.key, s]))
    const filtersFor = (key: string) => this.mergeDateRange(baseFilters, selected.get(key))

    const [overview, demographics, departments, positions, leave, performance, exit, turnover, learning] = await Promise.all([
      selected.has("overview")
        ? Promise.all([
            this.hrAnalyticsService.totalStaff(filtersFor("overview")),
            this.hrAnalyticsService.averageAge(filtersFor("overview")),
            this.hrAnalyticsService.bandDistribution(filtersFor("overview")),
          ]).then(([totalStaff, averageAge, bandDistribution]) => ({ totalStaff, averageAge, bandDistribution }))
        : Promise.resolve(null),
      selected.has("demographics") ? this.hrAnalyticsService.employeeDemographics(filtersFor("demographics")) : Promise.resolve(null),
      selected.has("departments")
        ? Promise.all([
            this.hrAnalyticsService.employeeDistributionByDepartment(filtersFor("departments")),
            this.hrAnalyticsService.orgStructureAnalytics(filtersFor("departments")),
          ]).then(([employeeDistribution, orgStructure]) => ({ employeeDistribution, orgStructure }))
        : Promise.resolve(null),
      selected.has("positions") ? this.hrAnalyticsService.positionFillRate(filtersFor("positions")) : Promise.resolve(null),
      selected.has("leave")
        ? Promise.all([this.hrAnalyticsService.leaveUtilizationSummary(filtersFor("leave")), this.delegated.leaveSummary(filtersFor("leave"))]).then(([utilization, summary]) => ({
            utilization,
            summary,
          }))
        : Promise.resolve(null),
      selected.has("performance")
        ? Promise.all([this.delegated.performanceDistribution(filtersFor("performance")), this.delegated.performanceByDepartment(filtersFor("performance"))]).then(
            ([distribution, byDepartment]) => ({ distribution, byDepartment })
          )
        : Promise.resolve(null),
      selected.has("exit") ? this.hrAnalyticsService.exitSummary(filtersFor("exit")) : Promise.resolve(null),
      selected.has("turnover") ? this.hrAnalyticsService.attritionRate(filtersFor("turnover")) : Promise.resolve(null),
      selected.has("learning") ? this.delegated.learningAnalyticsFor(filtersFor("learning")) : Promise.resolve(null),
    ])

    return { overview, demographics, departments, positions, leave, performance, exit, turnover, learning }
  }

  /** Same rule-based-summary spirit as buildInsights() above, but one line
   *  (or a few) per selected section instead of a single flat list, so each
   *  section of the custom report carries its own narrative takeaway. */
  private buildCustomInsights(bundle: CustomReportBundle): Record<string, string[]> {
    const insights: Record<string, string[]> = {}

    if (bundle.overview) {
      const lines: string[] = [`${bundle.overview.totalStaff.newJoined} joined and ${bundle.overview.totalStaff.exited} exited in the selected period.`]
      if (bundle.overview.totalStaff.changePercent !== null) {
        const direction = bundle.overview.totalStaff.changePercent >= 0 ? "grown" : "shrunk"
        lines.push(`Headcount has ${direction} by ${Math.abs(bundle.overview.totalStaff.changePercent)}% compared to last year.`)
      }
      insights.overview = lines
    }

    if (bundle.demographics) {
      const male = bundle.demographics.genderDistribution.find((g) => g.key === "MALE")?.count ?? 0
      const female = bundle.demographics.genderDistribution.find((g) => g.key === "FEMALE")?.count ?? 0
      const total = male + female
      insights.demographics =
        total > 0 ? [`Workforce is ${Math.round((male / total) * 100)}% male / ${Math.round((female / total) * 100)}% female across ${total} employees.`] : ["No gender data available for the selected period."]
    }

    if (bundle.departments) {
      const top = [...bundle.departments.employeeDistribution].sort((a, b) => b.count - a.count)[0]
      insights.departments = top ? [`${top.departmentName} is the largest department at ${top.count} employees (${top.percent}% of headcount).`] : ["No department data available."]
    }

    if (bundle.positions) {
      const vacant = bundle.positions.total - bundle.positions.filled
      insights.positions = [`${bundle.positions.fillRate}% of positions are filled (${vacant} vacant of ${bundle.positions.total} total).`]
    }

    if (bundle.leave) {
      insights.leave = [
        `Leave utilization is at ${bundle.leave.utilization.utilizationPercent}% (${bundle.leave.utilization.totalTaken} of ${bundle.leave.utilization.totalEntitlement} entitled days taken).`,
      ]
    }

    if (bundle.performance) {
      const mostVariance = [...bundle.performance.byDepartment].sort((a, b) => b.ratingStdDev - a.ratingStdDev)[0]
      insights.performance = mostVariance
        ? [`${mostVariance.departmentName} shows the widest spread in ratings (std. dev. ${mostVariance.ratingStdDev}), suggesting inconsistent rating calibration.`]
        : ["No performance review data available for the selected period."]
    }

    if (bundle.exit) {
      const top = bundle.exit.byReason[0]
      insights.exit = top ? [`"${top.label}" is the leading exit reason (${top.count} of ${bundle.exit.totalExits} departures).`] : ["No exits recorded for the selected period."]
    }

    if (bundle.turnover) {
      const direction = bundle.turnover.changePercent > 0 ? "increased" : bundle.turnover.changePercent < 0 ? "decreased" : "held steady"
      const magnitude = bundle.turnover.changePercent !== 0 ? ` by ${Math.abs(bundle.turnover.changePercent)} points` : ""
      insights.turnover = [`Attrition is at ${bundle.turnover.rate}% and has ${direction}${magnitude} vs. last year.`]
    }

    if (bundle.learning) {
      const amlLine = bundle.learning.amlCompletionRate !== null ? ` AML compliance is ${bundle.learning.amlCompletionRate}%.` : ""
      insights.learning = [`Training completion rate is ${bundle.learning.trainingCompletionRate}%.${amlLine}`]
    }

    return insights
  }

  async generateCustomReport(sections: CustomReportSectionInput[], baseFilters: HrAnalyticsFilters, format: "xlsx" | "pptx", actingEmployeeId?: string): Promise<Buffer> {
    const [bundle, cover] = await Promise.all([this.buildCustomBundle(sections, baseFilters), this.buildCoverInfo(baseFilters, actingEmployeeId)])
    const insights = this.buildCustomInsights(bundle)
    const recommendations = this.buildCustomRecommendations(bundle)
    return format === "pptx" ? this.generateCustomPptx(bundle, insights, recommendations, cover) : this.generateCustomExcel(bundle, insights, recommendations, cover)
  }

  private generateCustomExcel(bundle: CustomReportBundle, insights: Record<string, string[]>, recommendations: string[], cover: ReportCoverInfo): Buffer {
    const workbook = XLSX.utils.book_new()

    const coverSheet = XLSX.utils.aoa_to_sheet([
      [cover.reportTitle],
      [cover.periodLabel],
      ...(cover.departmentLabel ? [[`Department: ${cover.departmentLabel}`]] : []),
      [`Generated ${cover.generatedAtLabel} by ${cover.generatedByLabel}`],
    ])
    XLSX.utils.book_append_sheet(workbook, coverSheet, "Cover")

    const withInsights = (rows: (string | number)[][], key: string) => {
      if (insights[key]?.length) rows.push([], ["Insights"], ...insights[key].map((line) => [`• ${line}`]))
      return rows
    }
    const addSheet = (rows: (string | number)[][], key: string, sheetName: string) =>
      XLSX.utils.book_append_sheet(workbook, XLSX.utils.aoa_to_sheet(withInsights(rows, key)), sheetName)

    if (bundle.overview) {
      addSheet(
        [
          ["Overview & Headcount"],
          [],
          ["Total Active Staff", bundle.overview.totalStaff.activeCount],
          ["New Joiners (period)", bundle.overview.totalStaff.newJoined],
          ["Exits (period)", bundle.overview.totalStaff.exited],
          ["Change vs Last Year", bundle.overview.totalStaff.changePercent !== null ? `${bundle.overview.totalStaff.changePercent}%` : "N/A"],
          ["Average Age", bundle.overview.averageAge.overall ?? "N/A"],
          [],
          ["Band", "Count", "Percent"],
          ...bundle.overview.bandDistribution.map((b) => [b.bandName, b.count, `${b.percent}%`]),
        ],
        "overview",
        "Overview"
      )
    }

    if (bundle.demographics) {
      addSheet(
        [
          ["Gender Report"],
          [],
          ["Gender", "Count"],
          ...bundle.demographics.genderDistribution.map((g) => [g.label, g.count]),
          [],
          ["Age Bracket", "Count"],
          ...bundle.demographics.ageHistogram.map((a) => [a.bucket, a.count]),
          [],
          ["Contract Type", "Count"],
          ...bundle.demographics.contractTypeDistribution.map((c) => [c.label, c.count]),
        ],
        "demographics",
        "Gender Report"
      )
    }

    if (bundle.departments) {
      addSheet(
        [
          ["Departments"],
          [],
          ["Department", "Count", "Percent"],
          ...bundle.departments.employeeDistribution.map((d) => [d.departmentName, d.count, `${d.percent}%`]),
          [],
          ["Managers", bundle.departments.orgStructure.managersVsIndividualContributors.managers],
          ["Individual Contributors", bundle.departments.orgStructure.managersVsIndividualContributors.individualContributors],
          ["Average Span of Control", bundle.departments.orgStructure.averageSpanOfControl],
        ],
        "departments",
        "Departments"
      )
    }

    if (bundle.positions) {
      addSheet(
        [
          ["Positions"],
          [],
          ["Fill Rate", `${bundle.positions.fillRate}%`],
          ["Filled / Total", `${bundle.positions.filled} / ${bundle.positions.total}`],
          [],
          ["Department", "Filled", "Total", "Fill Rate"],
          ...bundle.positions.byDepartment.map((d) => [String(d.name), Number(d.filled), Number(d.total), `${d.fillRate}%`]),
        ],
        "positions",
        "Positions"
      )
    }

    if (bundle.leave) {
      addSheet(
        [
          ["Leave Report"],
          [],
          ["Utilization", `${bundle.leave.utilization.utilizationPercent}%`],
          ["Total Entitlement (days)", bundle.leave.utilization.totalEntitlement],
          ["Total Taken (days)", bundle.leave.utilization.totalTaken],
          ["Currently on Leave", bundle.leave.utilization.currentlyOnLeaveCount],
          [],
          ["Leave Type", "Days", "Requests"],
          ...bundle.leave.summary.byType.map((t) => [t.leaveTypeName, t.days, t.requests]),
          [],
          ["Department", "Days", "Requests"],
          ...bundle.leave.summary.byDepartment.map((d) => [d.departmentName, d.days, d.requests]),
        ],
        "leave",
        "Leave Report"
      )
    }

    if (bundle.performance) {
      addSheet(
        [
          ["Performance Report"],
          [],
          ["Rating", "Count", "Actual %", "Expected %"],
          ...bundle.performance.distribution.map((p) => [p.label, p.count, p.actualPercentage, p.expectedPercentage ?? "N/A"]),
          [],
          ["Department", "Avg. Rating", "Rating Std. Dev.", "Reviews"],
          ...bundle.performance.byDepartment.map((d) => [d.departmentName, d.averageRating, d.ratingStdDev, d.reviews]),
        ],
        "performance",
        "Performance Report"
      )
    }

    if (bundle.exit) {
      addSheet(
        [
          ["Exit Report"],
          [],
          ["Total Exits", bundle.exit.totalExits],
          [],
          ["Reason", "Count"],
          ...bundle.exit.byReason.map((r) => [r.label, r.count]),
          [],
          ["Type", "Count"],
          ...bundle.exit.byType.map((t) => [t.label, t.count]),
          [],
          ["Year", "Exits"],
          ...bundle.exit.trend.map((t) => [t.year, t.exits]),
        ],
        "exit",
        "Exit Report"
      )
    }

    if (bundle.turnover) {
      addSheet(
        [
          ["Turnover & Retention"],
          [],
          ["Attrition Rate", `${bundle.turnover.rate}%`],
          ["Previous Year", `${bundle.turnover.previousYearRate}%`],
          ["Change vs Last Year", `${bundle.turnover.changePercent}%`],
          ["Exits this Period", bundle.turnover.exits],
          [],
          ["Department", "Exits"],
          ...bundle.turnover.breakdown.byDepartment.map((d) => [d.label, d.count]),
        ],
        "turnover",
        "Turnover & Retention"
      )
    }

    if (bundle.learning) {
      addSheet(
        [
          ["Learning & Development"],
          [],
          ["Training Completion Rate", `${bundle.learning.trainingCompletionRate}%`],
          ["AML Compliance", bundle.learning.amlCompletionRate === null ? "Not tracked" : `${bundle.learning.amlCompletionRate}%`],
          [],
          ["Department", "Completion Rate", "Avg. Training Hours", "Avg. Training Cost", "Outstanding Mandatory"],
          ...bundle.learning.trainingCostAndHoursByDepartment.map((d) => [d.departmentName, `${d.completionRate}%`, d.averageTrainingHours, d.averageTrainingCost, d.outstandingMandatoryCourses]),
        ],
        "learning",
        "Learning & Development"
      )
    }

    if (recommendations.length > 0) {
      XLSX.utils.book_append_sheet(
        workbook,
        XLSX.utils.aoa_to_sheet([
          ["Recommendations"],
          ["Auto-generated from configurable business-rule thresholds — review before circulating."],
          [],
          ...recommendations.map((line) => [line]),
        ]),
        "Recommendations"
      )
    }

    return XLSX.write(workbook, { type: "buffer", bookType: "xlsx" }) as Buffer
  }

  // ==== HR Statistics Snapshot (single-page infographic PDF) =====================
  // A purpose-built, visually distinct export — not built from ExportBundle
  // like generatePdf() above (the full multi-section report). Calls
  // HrAnalyticsService.workforceSnapshot() directly and hand-lays-out every
  // element with PDFKit's coordinate-based drawing API: this codebase has no
  // HTML/CSS-to-PDF pipeline (see this file's own doc comment), so an exact
  // pixel match to a designed reference image isn't achievable — this gets
  // as close as PDFKit's primitives reasonably allow. NOTE: PDFKit's color
  // parser silently no-ops on bare hex ("B8860B") and needs the "#" prefix
  // ("#B8860B") — every color literal below is prefixed for that reason
  // (REPORT_THEME's own values are NOT prefixed, which is a separate,
  // pre-existing issue in the other export paths above; left alone here
  // since fixing that is outside what was asked).
  async generateSnapshotPdf(filters: HrAnalyticsFilters, actingEmployeeId?: string): Promise<Buffer> {
    const [snapshot, cover] = await Promise.all([this.hrAnalyticsService.workforceSnapshot(filters), this.buildCoverInfo(filters, actingEmployeeId)])

    const doc = new PDFDocument({ margin: 0, size: "A4" })
    const chunks: Buffer[] = []
    doc.on("data", (chunk: Buffer) => chunks.push(chunk))
    const done = new Promise<Buffer>((resolve) => doc.on("end", () => resolve(Buffer.concat(chunks))))

    this.renderSnapshotPage(doc, snapshot, cover)

    doc.end()
    return done
  }

  private renderSnapshotPage(doc: PDFKit.PDFDocument, snapshot: Awaited<ReturnType<HrAnalyticsService["workforceSnapshot"]>>, cover: ReportCoverInfo) {
    const PAGE_W = doc.page.width
    const PAGE_H = doc.page.height
    const MARGIN = 36
    const CONTENT_W = PAGE_W - MARGIN * 2

    const CREAM = "#F6F1E7"
    const CARD_BG = "#FCF8EF"
    const DARK_BROWN = "#2A1B12"
    const GOLD = "#B8860B"
    const TEXT_MUTED = "#7A6A57"
    const TRACK = "#E9DFC9"
    const ROSE = "#D4537E"
    const TEAL = "#2E7D6B"

    doc.rect(0, 0, PAGE_W, PAGE_H).fill(CREAM)

    // ---- Header band ----
    const headerH = 96
    doc.rect(0, 0, PAGE_W, headerH).fill(DARK_BROWN)
    doc.rect(0, headerH, PAGE_W, 3).fill(GOLD)

    const logoPath = resolveLogoPath()
    let headerLeftX = MARGIN
    if (logoPath) {
      doc.image(logoPath, headerLeftX, 18, { width: 60 })
      headerLeftX += 72
    }
    doc.fillColor(GOLD).font("Helvetica-Bold").fontSize(24).text("HR STATISTICS", headerLeftX, 22)
    doc.fillColor(CREAM).font("Helvetica").fontSize(10).text("NCBA Rwanda · People & Culture Workforce Snapshot", headerLeftX, 52)

    doc.fillColor(CREAM).font("Helvetica").fontSize(9)
    doc.text(snapshot.periodLabel, 0, 22, { width: PAGE_W - MARGIN, align: "right" })
    if (cover.departmentLabel) doc.text(`Department: ${cover.departmentLabel}`, 0, 38, { width: PAGE_W - MARGIN, align: "right" })
    doc.text(`Generated ${cover.generatedAtLabel}`, 0, 54, { width: PAGE_W - MARGIN, align: "right" })

    let y = headerH + 20

    // ---- Workforce at a glance (stat cards) ----
    doc.fillColor(DARK_BROWN).font("Helvetica-Bold").fontSize(12).text("WORKFORCE AT A GLANCE", MARGIN, y)
    y += 18

    const cardGap = 10
    const cardW = (CONTENT_W - cardGap * 3) / 4
    const cardH = 58
    const cardColors = [DARK_BROWN, GOLD, TEAL, ROSE]
    snapshot.byEmploymentType.forEach((row, i) => {
      const x = MARGIN + i * (cardW + cardGap)
      doc.roundedRect(x, y, cardW, cardH, 6).fill(CARD_BG)
      doc.rect(x, y, 4, cardH).fill(cardColors[i % cardColors.length])
      doc.fillColor(DARK_BROWN).font("Helvetica-Bold").fontSize(20).text(String(row.count), x + 12, y + 10)
      doc.fillColor(TEXT_MUTED).font("Helvetica").fontSize(8).text(`${row.label} (${row.percent}%)`, x + 12, y + 34, { width: cardW - 20 })
    })
    y += cardH + 26

    // ---- Gender split + Age distribution (two columns) ----
    const colGap = 24
    const colW = (CONTENT_W - colGap) / 2
    const leftX = MARGIN
    const rightX = MARGIN + colW + colGap

    doc.fillColor(DARK_BROWN).font("Helvetica-Bold").fontSize(12).text("GENDER SPLIT", leftX, y)
    doc.text("AGE DISTRIBUTION", rightX, y)
    const sectionTopY = y + 20

    const donutCx = leftX + 55
    const donutCy = sectionTopY + 55
    const outerR = 50
    const innerR = 28
    const genderSegments = [
      { value: snapshot.gender.male.count, color: DARK_BROWN },
      { value: snapshot.gender.female.count, color: ROSE },
    ]
    this.drawDonutChart(doc, donutCx, donutCy, outerR, innerR, genderSegments, CREAM)

    const genderLegend = [
      { label: "Male", count: snapshot.gender.male.count, percent: snapshot.gender.male.percent, color: DARK_BROWN },
      { label: "Female", count: snapshot.gender.female.count, percent: snapshot.gender.female.percent, color: ROSE },
    ]
    let legendY = sectionTopY + 8
    const legendX = leftX + 125
    for (const seg of genderLegend) {
      doc.rect(legendX, legendY, 10, 10).fill(seg.color)
      doc.fillColor(DARK_BROWN).font("Helvetica").fontSize(9).text(`${seg.label}: ${seg.count} (${seg.percent}%)`, legendX + 16, legendY - 1)
      legendY += 20
    }

    const ageMax = Math.max(1, ...snapshot.ageDistribution.map((a) => a.count))
    this.drawBarList(
      doc,
      rightX,
      sectionTopY,
      colW,
      snapshot.ageDistribution.map((a) => ({ label: a.bucket, value: a.count, percent: a.percent, color: GOLD })),
      ageMax,
      DARK_BROWN,
      TEXT_MUTED,
      TRACK
    )

    y = sectionTopY + 120

    // ---- Tenure + Band distribution (two columns) ----
    doc.fillColor(DARK_BROWN).font("Helvetica-Bold").fontSize(12).text("TENURE DISTRIBUTION", leftX, y)
    doc.text("BAND DISTRIBUTION", rightX, y)
    const sectionTopY2 = y + 20

    const tenureMax = Math.max(1, ...snapshot.tenureDistribution.map((t) => t.count))
    this.drawBarList(
      doc,
      leftX,
      sectionTopY2,
      colW,
      snapshot.tenureDistribution.map((t) => ({ label: t.bucket, value: t.count, percent: t.percent, color: TEAL })),
      tenureMax,
      DARK_BROWN,
      TEXT_MUTED,
      TRACK
    )

    const bandMax = Math.max(1, ...snapshot.bandDistributionGrouped.map((b) => b.count))
    this.drawBarList(
      doc,
      rightX,
      sectionTopY2,
      colW,
      snapshot.bandDistributionGrouped.map((b) => ({ label: b.label, value: b.count, percent: b.percent, color: DARK_BROWN })),
      bandMax,
      DARK_BROWN,
      TEXT_MUTED,
      TRACK
    )
    doc.fillColor(TEXT_MUTED).font("Helvetica-Oblique").fontSize(7).text(`Based on ${snapshot.permanentStaffCount} permanent staff`, rightX, sectionTopY2 + 100)

    y = sectionTopY2 + 120

    // ---- Turnover & exits ----
    doc.fillColor(DARK_BROWN).font("Helvetica-Bold").fontSize(12).text("TURNOVER & EXITS", MARGIN, y)
    y += 18
    doc
      .fillColor(TEXT_MUTED)
      .font("Helvetica")
      .fontSize(8)
      .text(`${snapshot.turnover.totalExits} exits this period · overall turnover ${snapshot.turnover.overallRatePercent}%`, MARGIN, y)
    y += 16

    this.drawBarList(
      doc,
      MARGIN,
      y,
      CONTENT_W,
      [
        {
          label: "Permanent",
          value: snapshot.turnover.permanent.ratePercent,
          percent: snapshot.turnover.permanent.ratePercent,
          color: DARK_BROWN,
          displayValue: `${snapshot.turnover.permanent.ratePercent}% · ${snapshot.turnover.permanent.exits} exits`,
        },
        {
          label: "DSA / Intern",
          value: snapshot.turnover.contractual.ratePercent,
          percent: snapshot.turnover.contractual.ratePercent,
          color: GOLD,
          displayValue: `${snapshot.turnover.contractual.ratePercent}% · ${snapshot.turnover.contractual.exits} exits`,
        },
      ],
      Math.max(1, snapshot.turnover.permanent.ratePercent, snapshot.turnover.contractual.ratePercent),
      DARK_BROWN,
      TEXT_MUTED,
      TRACK
    )
    y += 56

    // Regrettable vs. non-regrettable — 100%-stacked bar
    doc.fillColor(DARK_BROWN).font("Helvetica-Bold").fontSize(9).text("Regrettable vs. Non-Regrettable Exits", MARGIN, y)
    y += 14
    const stackW = CONTENT_W
    const stackH = 20
    const regPct = snapshot.exitType.regrettable.percent
    const nonRegPct = snapshot.exitType.nonRegrettable.percent
    const totalPct = regPct + nonRegPct
    const regW = totalPct === 0 ? stackW / 2 : (regPct / totalPct) * stackW
    doc.roundedRect(MARGIN, y, stackW, stackH, 4).fill(TRACK)
    if (totalPct > 0) {
      doc.rect(MARGIN, y, regW, stackH).fill(ROSE)
      doc.rect(MARGIN + regW, y, stackW - regW, stackH).fill(TEAL)
    }
    doc.fillColor("#FFFFFF").font("Helvetica-Bold").fontSize(8)
    if (regW > 60) doc.text(`Regrettable ${regPct}%`, MARGIN + 8, y + 6)
    if (stackW - regW > 60) doc.text(`Non-regrettable ${nonRegPct}%`, MARGIN + regW + 8, y + 6)
    y += stackH + 22

    // ---- Key takeaways ----
    doc.fillColor(DARK_BROWN).font("Helvetica-Bold").fontSize(12).text("KEY TAKEAWAYS", MARGIN, y)
    y += 18
    const takeawayGap = 10
    const takeawayW = (CONTENT_W - takeawayGap * 2) / 3
    const takeawayH = 70
    snapshot.keyTakeaways.slice(0, 3).forEach((line, i) => {
      const x = MARGIN + i * (takeawayW + takeawayGap)
      doc.roundedRect(x, y, takeawayW, takeawayH, 6).fill(DARK_BROWN)
      doc.fillColor(GOLD).font("Helvetica-Bold").fontSize(14).text(String(i + 1), x + 10, y + 8)
      doc.fillColor(CREAM).font("Helvetica").fontSize(8).text(line, x + 10, y + 26, { width: takeawayW - 20 })
    })

    // ---- Footer ----
    const footerY = PAGE_H - 34
    doc.rect(0, footerY, PAGE_W, 2).fill(GOLD)
    doc.fillColor(TEXT_MUTED).font("Helvetica").fontSize(7)
    doc.text("Prepared by NCBA Rwanda PeopleSuite — CONFIDENTIAL — INTERNAL USE ONLY", MARGIN, footerY + 8)
    doc.text(`Generated by: ${cover.generatedByLabel}`, 0, footerY + 8, { width: PAGE_W - MARGIN, align: "right" })

    doc.fillColor("black").font("Helvetica")
  }

  /** Hand-drawn donut chart — PDFKit has no native pie/donut primitive, so
   *  each segment is built as a filled wedge (polyline of points along the
   *  outer-radius arc, closed back to center) and the hole is punched by
   *  drawing a background-colored circle of `innerR` on top afterward. */
  private drawDonutChart(doc: PDFKit.PDFDocument, cx: number, cy: number, outerR: number, innerR: number, segments: { value: number; color: string }[], holeColor: string) {
    const total = segments.reduce((sum, s) => sum + s.value, 0)
    if (total <= 0) {
      doc.circle(cx, cy, outerR).fill("#E9DFC9")
      doc.circle(cx, cy, innerR).fill(holeColor)
      return
    }
    let startAngle = -Math.PI / 2
    for (const seg of segments) {
      if (seg.value <= 0) continue
      const sweep = (seg.value / total) * Math.PI * 2
      const endAngle = startAngle + sweep
      const steps = Math.max(2, Math.ceil((sweep / (Math.PI * 2)) * 120))
      doc.moveTo(cx, cy)
      for (let i = 0; i <= steps; i++) {
        const t = startAngle + (sweep * i) / steps
        doc.lineTo(cx + outerR * Math.cos(t), cy + outerR * Math.sin(t))
      }
      doc.closePath()
      doc.fill(seg.color)
      startAngle = endAngle
    }
    doc.circle(cx, cy, innerR).fill(holeColor)
  }

  /** Compact horizontal bar-list used for every distribution section of the
   *  snapshot (age/tenure/band/turnover) — a label, a proportional bar
   *  against `maxValue`, and a right-hand value label (defaulting to
   *  "value (percent%)", overridable via `displayValue` for rows like
   *  turnover that want a different string). */
  private drawBarList(
    doc: PDFKit.PDFDocument,
    x: number,
    y: number,
    width: number,
    rows: { label: string; value: number; percent: number; color: string; displayValue?: string }[],
    maxValue: number,
    labelColor: string,
    valueColor: string,
    trackColor: string
  ) {
    const barHeight = 12
    const rowGap = 10
    const labelW = 68
    const valueW = 78
    const barMaxW = width - labelW - valueW
    rows.forEach((row, i) => {
      const rowY = y + i * (barHeight + rowGap)
      doc.fillColor(labelColor).font("Helvetica").fontSize(8).text(row.label, x, rowY + 2, { width: labelW })
      const barX = x + labelW
      doc.roundedRect(barX, rowY, barMaxW, barHeight, 3).fill(trackColor)
      const barW = maxValue === 0 ? 0 : Math.max(2, (row.value / maxValue) * barMaxW)
      doc.roundedRect(barX, rowY, barW, barHeight, 3).fill(row.color)
      doc
        .fillColor(valueColor)
        .font("Helvetica")
        .fontSize(7.5)
        .text(row.displayValue ?? `${row.value} (${row.percent}%)`, barX + barMaxW + 6, rowY + 2, { width: valueW })
    })
  }

  private async generateCustomPptx(bundle: CustomReportBundle, insights: Record<string, string[]>, recommendations: string[], cover: ReportCoverInfo): Promise<Buffer> {
    const pptx = new PptxGenJS()
    pptx.defineLayout({ name: "A4", width: 10, height: 7.5 })
    pptx.layout = "A4"

    this.addCoverSlide(pptx, cover, "Custom HR Report")

    /** Every section gets a data slide (table or chart) plus, when a
     *  narrative insight exists for it, a second slide with bullet points —
     *  same "Key HR Insights" pattern as the fixed-format export, just
     *  scoped per-section instead of one shared slide at the end. */
    const addInsightsSlide = (title: string, key: string) => {
      const lines = insights[key]
      if (!lines?.length) return
      const slide = pptx.addSlide()
      slide.addText(`${title} — Insights`, { x: 0.4, y: 0.3, fontSize: 22, bold: true, color: "0A2647" })
      slide.addText(
        lines.map((line) => ({ text: line, options: { bullet: true, breakLine: true } })),
        { x: 0.5, y: 1.1, w: 9, h: 5, fontSize: 14, color: "333333" }
      )
    }

    if (bundle.overview) {
      const slide = pptx.addSlide()
      slide.addText("Overview & Headcount", { x: 0.4, y: 0.3, fontSize: 22, bold: true, color: "0A2647" })
      slide.addTable(
        [
          tableRow(["Metric", "Value"]),
          tableRow(["Total Active Staff", String(bundle.overview.totalStaff.activeCount)]),
          tableRow(["New Joiners (period)", String(bundle.overview.totalStaff.newJoined)]),
          tableRow(["Exits (period)", String(bundle.overview.totalStaff.exited)]),
          tableRow(["Average Age", String(bundle.overview.averageAge.overall ?? "N/A")]),
        ],
        { x: 0.4, y: 1.0, w: 9, colW: [5, 4], fontSize: 12, border: { type: "solid", color: "CCCCCC", pt: 0.5 } }
      )
      addInsightsSlide("Overview & Headcount", "overview")
    }

    if (bundle.demographics) {
      const slide = pptx.addSlide()
      slide.addText("Gender Report", { x: 0.4, y: 0.3, fontSize: 22, bold: true, color: "0A2647" })
      slide.addChart(
        pptx.ChartType.doughnut,
        [{ name: "Employees", labels: bundle.demographics.genderDistribution.map((g) => g.label), values: bundle.demographics.genderDistribution.map((g) => g.count) }],
        { x: 1.5, y: 1.0, w: 7, h: 5.5 }
      )
      addInsightsSlide("Gender Report", "demographics")
    }

    if (bundle.departments) {
      const slide = pptx.addSlide()
      slide.addText("Departments", { x: 0.4, y: 0.3, fontSize: 22, bold: true, color: "0A2647" })
      slide.addChart(
        pptx.ChartType.bar,
        [{ name: "Employees", labels: bundle.departments.employeeDistribution.map((d) => d.departmentName), values: bundle.departments.employeeDistribution.map((d) => d.count) }],
        { x: 0.5, y: 1.0, w: 9, h: 5.5 }
      )
      addInsightsSlide("Departments", "departments")
    }

    if (bundle.positions) {
      const slide = pptx.addSlide()
      slide.addText("Positions — Fill Rate by Department", { x: 0.4, y: 0.3, fontSize: 22, bold: true, color: "0A2647" })
      slide.addChart(
        pptx.ChartType.bar,
        [{ name: "Fill Rate %", labels: bundle.positions.byDepartment.map((d) => String(d.name)), values: bundle.positions.byDepartment.map((d) => Number(d.fillRate)) }],
        { x: 0.5, y: 1.0, w: 9, h: 5.5 }
      )
      addInsightsSlide("Positions", "positions")
    }

    if (bundle.leave) {
      const slide = pptx.addSlide()
      slide.addText("Leave Report", { x: 0.4, y: 0.3, fontSize: 22, bold: true, color: "0A2647" })
      slide.addChart(
        pptx.ChartType.bar,
        [{ name: "Days Taken", labels: bundle.leave.summary.byType.map((t) => t.leaveTypeName), values: bundle.leave.summary.byType.map((t) => t.days) }],
        { x: 0.5, y: 1.0, w: 9, h: 5.5 }
      )
      addInsightsSlide("Leave Report", "leave")
    }

    if (bundle.performance) {
      const slide = pptx.addSlide()
      slide.addText("Performance Report", { x: 0.4, y: 0.3, fontSize: 22, bold: true, color: "0A2647" })
      slide.addChart(
        pptx.ChartType.bar,
        [{ name: "% of reviews", labels: bundle.performance.distribution.map((p) => p.label), values: bundle.performance.distribution.map((p) => p.actualPercentage) }],
        { x: 0.5, y: 1.0, w: 9, h: 5.5 }
      )
      addInsightsSlide("Performance Report", "performance")
    }

    if (bundle.exit) {
      const slide = pptx.addSlide()
      slide.addText("Exit Report", { x: 0.4, y: 0.3, fontSize: 22, bold: true, color: "0A2647" })
      slide.addChart(
        pptx.ChartType.bar,
        [{ name: "Exits", labels: bundle.exit.byReason.map((r) => r.label), values: bundle.exit.byReason.map((r) => r.count) }],
        { x: 0.5, y: 1.0, w: 9, h: 5.5 }
      )
      addInsightsSlide("Exit Report", "exit")
    }

    if (bundle.turnover) {
      const slide = pptx.addSlide()
      slide.addText("Turnover & Retention", { x: 0.4, y: 0.3, fontSize: 22, bold: true, color: "0A2647" })
      slide.addTable(
        [
          tableRow(["Metric", "Value"]),
          tableRow(["Attrition Rate", `${bundle.turnover.rate}%`]),
          tableRow(["Previous Year", `${bundle.turnover.previousYearRate}%`]),
          tableRow(["Change vs Last Year", `${bundle.turnover.changePercent}%`]),
          tableRow(["Exits this Period", String(bundle.turnover.exits)]),
        ],
        { x: 0.4, y: 1.0, w: 9, colW: [5, 4], fontSize: 12, border: { type: "solid", color: "CCCCCC", pt: 0.5 } }
      )
      addInsightsSlide("Turnover & Retention", "turnover")
    }

    if (bundle.learning) {
      const slide = pptx.addSlide()
      slide.addText("Learning & Development", { x: 0.4, y: 0.3, fontSize: 22, bold: true, color: "0A2647" })
      slide.addTable(
        [
          tableRow(["Metric", "Value"]),
          tableRow(["Training Completion Rate", `${bundle.learning.trainingCompletionRate}%`]),
          tableRow(["AML Compliance", bundle.learning.amlCompletionRate === null ? "Not tracked" : `${bundle.learning.amlCompletionRate}%`]),
        ],
        { x: 0.4, y: 1.0, w: 9, colW: [5, 4], fontSize: 12, border: { type: "solid", color: "CCCCCC", pt: 0.5 } }
      )
      addInsightsSlide("Learning & Development", "learning")
    }

    if (recommendations.length > 0) {
      const slide = pptx.addSlide()
      slide.addText("Recommendations", { x: 0.4, y: 0.3, fontSize: 22, bold: true, color: "0A2647" })
      slide.addText("Auto-generated from configurable business-rule thresholds — review before circulating.", {
        x: 0.4,
        y: 0.85,
        w: 9,
        fontSize: 10,
        italic: true,
        color: "888888",
      })
      slide.addText(
        recommendations.map((line) => ({ text: line, options: { bullet: true, breakLine: true } })),
        { x: 0.5, y: 1.3, w: 9, h: 4.8, fontSize: 14, color: "333333" }
      )
    }

    const output = await pptx.write({ outputType: "nodebuffer" })
    return output as Buffer
  }
}
